pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'git_accessToken',
                    url: 'https://github.com/enginedevp/UnnamedProject.git'
            }
        }
    }
}