version: '3'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - "30000:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      # sudo chmod 666 /var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock

      