pipeline {

    agent any
    
    environment {
        ID = credentials('dockerhub-id')
        PASSWORD = credentials('dockerhub-password') 
        IP = credentials('server-ip') 
        WORKSPACE = credentials('workspace') 
        KEY = credentials('ssh-key') 
        REDIS_IP = credentials('redis-ip') 
        REDIS_PORT = credentials('redis-port') 
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                    ./DevOps/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./DevOps/jenkins/build/build.sh
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                cd ScriptCrawler/server && npm run test
                '''

                // sh '''
                // ./DevOps/jenkins/test/mvn.sh mvn test
                // cd ./ScriptCrawler/server && npm run test
                // '''
            }
        }
        
        //     post {
        //         always {
        //             junit 'Backend/target/surefire-reports/*.xml'
        //         }
        //     }
        // }

        stage('Push') {
            steps {
                sh './DevOps/jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh './DevOps/jenkins/deploy/deploy.sh'
            }
        }
    }
}
